
//THIS IS AN AUTOGENERATED MODEL
/**
 * Copyright (c) 2017, Damian Vicino
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 1. Redistributions of source code must retain the above copyright notice,
 * this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 * this list of conditions and the following disclaimer in the documentation
 * and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#include <chrono>
#include <cadmium/modeling/coupling.hpp>
#include <cadmium/modeling/ports.hpp>
#include <cadmium/engine/pdevs_runner.hpp>
#include "cadmium-devstone-atomic.hpp"
#include "cadmium-event-reader.hpp"

// Ports for coupled models, we use the same in every level
struct coupled_in_port : public cadmium::in_port<int>{};
struct coupled_out_port : public cadmium::out_port<int>{};
using coupled_in_ports = std::tuple<coupled_in_port>;
using coupled_out_ports = std::tuple<coupled_out_port>;

//Devstones have no Internal coupling
using ics=std::tuple<>;

//A configured version of the devstone atomic, we use same configuration in every atomic.
template<typename TIME>
struct configured_atomic_devstone : devstone_atomic<TIME>{
    configured_atomic_devstone(){
        devstone_atomic<TIME>::period = 1;
        devstone_atomic<TIME>::external_cycles = 100;
        devstone_atomic<TIME>::internal_cycles = 100;
    }
};

//This model is LI devstone W=6, D=8
//Level 0 has always a single model
template<typename TIME>
struct devstone_atomic_L0_0 : configured_atomic_devstone<TIME>{};

//Level 1
//atomics
template<typename TIME>
struct devstone_atomic_L1_0 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L1_1 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L1_2 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L1_3 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L1_4 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L1_5 : configured_atomic_devstone<TIME>{};
//coupled
using L1_submodels=cadmium::modeling::models_tuple<devstone_atomic_L0_0>;
using L1_eics=std::tuple<
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L0_0, devstone_atomic_defs::in>
>;
using L1_eocs=std::tuple<
    cadmium::modeling::EOC<devstone_atomic_L0_0, devstone_atomic_defs::out, coupled_out_port>
>;
template<typename TIME>
using L1_coupled=cadmium::modeling::pdevs::coupled_model<TIME, coupled_in_ports, coupled_out_ports, L1_submodels, L1_eics, L1_eocs, ics>;
//Level 2
//atomics
template<typename TIME>
struct devstone_atomic_L2_0 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L2_1 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L2_2 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L2_3 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L2_4 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L2_5 : configured_atomic_devstone<TIME>{};
//coupled
using L2_submodels=cadmium::modeling::models_tuple<devstone_atomic_L1_0, devstone_atomic_L1_1, devstone_atomic_L1_2, devstone_atomic_L1_3, devstone_atomic_L1_4, devstone_atomic_L1_5, L1_coupled>;

using L2_eics=std::tuple<
    cadmium::modeling::EIC<coupled_in_port, L1_coupled, coupled_in_port>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L1_0, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L1_1, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L1_2, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L1_3, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L1_4, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L1_5, devstone_atomic_defs::in>
>;
using L2_eocs=std::tuple<
    cadmium::modeling::EOC<L1_coupled,coupled_out_port, coupled_out_port>
>;
template<typename TIME>
using L2_coupled=cadmium::modeling::pdevs::coupled_model<TIME, coupled_in_ports, coupled_out_ports, L2_submodels, L2_eics, L2_eocs, ics>;
//Level 3
//atomics
template<typename TIME>
struct devstone_atomic_L3_0 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L3_1 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L3_2 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L3_3 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L3_4 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L3_5 : configured_atomic_devstone<TIME>{};
//coupled
using L3_submodels=cadmium::modeling::models_tuple<devstone_atomic_L2_0, devstone_atomic_L2_1, devstone_atomic_L2_2, devstone_atomic_L2_3, devstone_atomic_L2_4, devstone_atomic_L2_5, L2_coupled>;

using L3_eics=std::tuple<
    cadmium::modeling::EIC<coupled_in_port, L2_coupled, coupled_in_port>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L2_0, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L2_1, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L2_2, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L2_3, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L2_4, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L2_5, devstone_atomic_defs::in>
>;
using L3_eocs=std::tuple<
    cadmium::modeling::EOC<L2_coupled,coupled_out_port, coupled_out_port>
>;
template<typename TIME>
using L3_coupled=cadmium::modeling::pdevs::coupled_model<TIME, coupled_in_ports, coupled_out_ports, L3_submodels, L3_eics, L3_eocs, ics>;
//Level 4
//atomics
template<typename TIME>
struct devstone_atomic_L4_0 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L4_1 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L4_2 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L4_3 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L4_4 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L4_5 : configured_atomic_devstone<TIME>{};
//coupled
using L4_submodels=cadmium::modeling::models_tuple<devstone_atomic_L3_0, devstone_atomic_L3_1, devstone_atomic_L3_2, devstone_atomic_L3_3, devstone_atomic_L3_4, devstone_atomic_L3_5, L3_coupled>;

using L4_eics=std::tuple<
    cadmium::modeling::EIC<coupled_in_port, L3_coupled, coupled_in_port>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L3_0, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L3_1, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L3_2, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L3_3, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L3_4, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L3_5, devstone_atomic_defs::in>
>;
using L4_eocs=std::tuple<
    cadmium::modeling::EOC<L3_coupled,coupled_out_port, coupled_out_port>
>;
template<typename TIME>
using L4_coupled=cadmium::modeling::pdevs::coupled_model<TIME, coupled_in_ports, coupled_out_ports, L4_submodels, L4_eics, L4_eocs, ics>;
//Level 5
//atomics
template<typename TIME>
struct devstone_atomic_L5_0 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L5_1 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L5_2 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L5_3 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L5_4 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L5_5 : configured_atomic_devstone<TIME>{};
//coupled
using L5_submodels=cadmium::modeling::models_tuple<devstone_atomic_L4_0, devstone_atomic_L4_1, devstone_atomic_L4_2, devstone_atomic_L4_3, devstone_atomic_L4_4, devstone_atomic_L4_5, L4_coupled>;

using L5_eics=std::tuple<
    cadmium::modeling::EIC<coupled_in_port, L4_coupled, coupled_in_port>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L4_0, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L4_1, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L4_2, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L4_3, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L4_4, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L4_5, devstone_atomic_defs::in>
>;
using L5_eocs=std::tuple<
    cadmium::modeling::EOC<L4_coupled,coupled_out_port, coupled_out_port>
>;
template<typename TIME>
using L5_coupled=cadmium::modeling::pdevs::coupled_model<TIME, coupled_in_ports, coupled_out_ports, L5_submodels, L5_eics, L5_eocs, ics>;
//Level 6
//atomics
template<typename TIME>
struct devstone_atomic_L6_0 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L6_1 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L6_2 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L6_3 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L6_4 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L6_5 : configured_atomic_devstone<TIME>{};
//coupled
using L6_submodels=cadmium::modeling::models_tuple<devstone_atomic_L5_0, devstone_atomic_L5_1, devstone_atomic_L5_2, devstone_atomic_L5_3, devstone_atomic_L5_4, devstone_atomic_L5_5, L5_coupled>;

using L6_eics=std::tuple<
    cadmium::modeling::EIC<coupled_in_port, L5_coupled, coupled_in_port>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L5_0, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L5_1, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L5_2, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L5_3, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L5_4, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L5_5, devstone_atomic_defs::in>
>;
using L6_eocs=std::tuple<
    cadmium::modeling::EOC<L5_coupled,coupled_out_port, coupled_out_port>
>;
template<typename TIME>
using L6_coupled=cadmium::modeling::pdevs::coupled_model<TIME, coupled_in_ports, coupled_out_ports, L6_submodels, L6_eics, L6_eocs, ics>;
//Level 7
//atomics
template<typename TIME>
struct devstone_atomic_L7_0 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L7_1 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L7_2 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L7_3 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L7_4 : configured_atomic_devstone<TIME>{};
template<typename TIME>
struct devstone_atomic_L7_5 : configured_atomic_devstone<TIME>{};
//coupled
using L7_submodels=cadmium::modeling::models_tuple<devstone_atomic_L6_0, devstone_atomic_L6_1, devstone_atomic_L6_2, devstone_atomic_L6_3, devstone_atomic_L6_4, devstone_atomic_L6_5, L6_coupled>;

using L7_eics=std::tuple<
    cadmium::modeling::EIC<coupled_in_port, L6_coupled, coupled_in_port>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L6_0, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L6_1, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L6_2, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L6_3, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L6_4, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L6_5, devstone_atomic_defs::in>
>;
using L7_eocs=std::tuple<
    cadmium::modeling::EOC<L6_coupled,coupled_out_port, coupled_out_port>
>;
template<typename TIME>
using L7_coupled=cadmium::modeling::pdevs::coupled_model<TIME, coupled_in_ports, coupled_out_ports, L7_submodels, L7_eics, L7_eocs, ics>;

//Level 8 has no atomics because it is the last level
//coupled
using L8_submodels=cadmium::modeling::models_tuple<devstone_atomic_L7_0, devstone_atomic_L7_1, devstone_atomic_L7_2, devstone_atomic_L7_3, devstone_atomic_L7_4, devstone_atomic_L7_5, L7_coupled>;

using L8_eics=std::tuple<
    cadmium::modeling::EIC<coupled_in_port, L7_coupled, coupled_in_port>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L7_0, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L7_1, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L7_2, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L7_3, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L7_4, devstone_atomic_defs::in>,
    cadmium::modeling::EIC<coupled_in_port, devstone_atomic_L7_5, devstone_atomic_defs::in>
>;
using L8_eocs=std::tuple<
    cadmium::modeling::EOC<L7_coupled,coupled_out_port, coupled_out_port>
>;
template<typename TIME>
using L8_coupled=cadmium::modeling::pdevs::coupled_model<TIME, coupled_in_ports, coupled_out_ports, L8_submodels, L8_eics, L8_eocs, ics>;

//TOP model conecting a generator of events to the input
using TOP_coupled_in_ports=std::tuple<>;
using TOP_coupled_out_ports=std::tuple<>;
using TOP_submodels=cadmium::modeling::models_tuple<devstone_event_reader, L8_coupled>;
using TOP_eics=std::tuple<>;
using TOP_eocs=std::tuple<>;
using TOP_ics=std::tuple<
cadmium::modeling::IC<devstone_event_reader, devstone_event_reader_defs::out, L8_coupled, coupled_in_port>
>;
template<typename TIME>
using TOP_coupled=cadmium::modeling::pdevs::coupled_model<TIME, TOP_coupled_in_ports, TOP_coupled_out_ports, TOP_submodels, TOP_eics, TOP_eocs, TOP_ics>;

using hclock=std::chrono::high_resolution_clock; //for measuring execution time

int main(){
    auto start = hclock::now(); //to measure simulation execution time
    cadmium::engine::runner<float, TOP_coupled, cadmium::logger::not_logger> r{0.0};
        
    r.run_until_passivate();
    
    auto elapsed = std::chrono::duration_cast<std::chrono::duration<double, std::ratio<1>>>
    (hclock::now() - start).count();
    std::cout << "Simulation took:" << elapsed << "sec" << std::endl;
    return 0;
}
